export const envs = {
  API_KEY: process.env.NEXT_PUBLIC_API_KEY,
  AUTH_DOMAIN: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
  PROJECT_ID: process.env.NEXT_PUBLIC_PROJECT_ID,
  STORAGE_BUCKET: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
  MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
  APP_ID: process.env.NEXT_PUBLIC_APP_ID,
  CONTACT_EMAIL_AUTH: process.env.CONTACT_EMAIL_AUTH_TRID,
  CONTACT_EMAIL: process.env.CONTACT_EMAIL,
  SUPPORT_EMAIL: process.env.SUPPORT_EMAIL,
  CONTACT_JAAFU_AUTH_TRID: process.env.CONTACT_JAAFU_AUTH_TRID,
};
